# Generated by Django 4.2.3 on 2023-08-09 15:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteo',
            options={'permissions': [('can_edit_all', 'Can edit all content')]},
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
